[6011](https://www.codeup.kr/problem.php?id=6011). 변수에 실수값을 저장한 후
변수에 저장되어 있는 값을 그대로 출력해보자.

In [ ]:
x = float(input())
print(x)

[6012](https://www.codeup.kr/problem.php?id=6012). 줄을 바꿔 정수(integer) 2개를 입력받아 줄을 바꿔 출력해보자.

In [ ]:
a = int(input())
b = int(input())
print(a)
print(b)

[6013](https://www.codeup.kr/problem.php?id=6013). 줄을 바꿔 문자(character) 2개를 입력받고, 순서를 바꿔 한 줄씩 출력해보자.

In [ ]:
a = str(input())
b = str(input())
# 순서 바꾸기
print(b)
print(a)

[6014](https://www.codeup.kr/problem.php?id=6014). 실수(real number) 1개를 입력받아 줄을 바꿔 3번 출력해보자.

In [ ]:
x = float(input())
print(x)
print(x)
print(x)

[6015](https://www.codeup.kr/problem.php?id=6015). 공백을 두고 입력된정수(integer) 2개를 입력받아 줄을 바꿔 출력해보자.

In [ ]:
a, b  = input().split()
print(int(a))
print(int(b))
# map()과 list() 함수를 사용하는 방법도 있음

[6016](https://www.codeup.kr/problem.php?id=6016). 공백을 두고 문자(character) 2개를 입력받아 순서를 바꿔 출력해보자.

In [ ]:
a, b  = input().split()
print(str(b), str(a))

[6017](https://www.codeup.kr/problem.php?id=6017). 정수(integer), 실수, 문자(character), 문자열(string) 등 1개만 입력받아 한 줄로 3번 출력해보자.

In [ ]:
x = input()
print(x, x, x)

[6018](https://colab.research.google.com/drive/1K6K6CpkdmDzl8okbcKHQqKVK3hMBkuJY#scrollTo=gustLWo3NM20&line=1&uniqifier=1). 24시간 시:분 형식으로 시간이 입력될 때, 그대로 출력해보자.

In [ ]:
# x = input()
# print(x)
a, b = input().split(':')
print(a, b, sep=':')

[6019](https://www.codeup.kr/problem.php?id=6019). "연도.월.일"을 입력받아 "일-월-연도" 순서로 바꿔 출력해보자.

In [ ]:
y, m, d = input().split('.')
print(d, m, y, sep='-')

[6020](https://www.codeup.kr/problem.php?id=6020). 왼쪽 6자리는 생년월일(YYMMDD)이고 오른쪽 7자리는 성별, 출생지역,확인코드로 구성되어있다.
주민번호를 입력받아 '-'를 제외한 주민번호 13자리를 모두 붙여 출력해보자.

In [ ]:
a, b = input().split('-')
print(a, b, sep='')